' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Namespace Gestionale_Condomini

    <Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
    Partial Class insAnno
        Inherits System.Windows.Forms.Form

        'Form overrides dispose to clean up the component list.
        <System.Diagnostics.DebuggerNonUserCode()> _
        Protected Overrides Sub Dispose(ByVal disposing As Boolean)
            Try
                If disposing AndAlso components IsNot Nothing Then
                    components.Dispose()
                End If
            Finally
                MyBase.Dispose(disposing)
            End Try
        End Sub

        'Required by the Windows Form Designer
        Private components As System.ComponentModel.IContainer

        'NOTE: The following procedure is required by the Windows Form Designer
        'It can be modified using the Windows Form Designer.  
        'Do not modify it using the code editor.
        <System.Diagnostics.DebuggerStepThrough()> _
        Private Sub InitializeComponent()
            Me.components = New System.ComponentModel.Container()
            Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(insAnno))
            Me.NewDataSet = New NewDataSet()
            Me.AnniBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.AnniBindingSource1 = New System.Windows.Forms.BindingSource(Me.components)
            Me.newanno = New System.Windows.Forms.TextBox()
            Me.Aggiungi = New System.Windows.Forms.Button()
            Me.Label2 = New System.Windows.Forms.Label()
            CType(Me.NewDataSet, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.AnniBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.AnniBindingSource1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.SuspendLayout()
            '
            'NewDataSet
            '
            Me.NewDataSet.DataSetName = "NewDataSet"
            Me.NewDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
            '
            'AnniBindingSource
            '
            Me.AnniBindingSource.DataMember = "Anni"
            Me.AnniBindingSource.DataSource = Me.NewDataSet
            '
            'AnniBindingSource1
            '
            Me.AnniBindingSource1.DataMember = "Anni"
            Me.AnniBindingSource1.DataSource = Me.NewDataSet
            '
            'newanno
            '
            Me.newanno.Location = New System.Drawing.Point(28, 45)
            Me.newanno.Name = "newanno"
            Me.newanno.Size = New System.Drawing.Size(63, 20)
            Me.newanno.TabIndex = 5
            '
            'Aggiungi
            '
            Me.Aggiungi.Location = New System.Drawing.Point(106, 45)
            Me.Aggiungi.Name = "Aggiungi"
            Me.Aggiungi.Size = New System.Drawing.Size(117, 23)
            Me.Aggiungi.TabIndex = 6
            Me.Aggiungi.Text = "Aggiungi Anno"
            Me.Aggiungi.UseVisualStyleBackColor = True
            '
            'Label2
            '
            Me.Label2.AutoSize = True
            Me.Label2.Location = New System.Drawing.Point(28, 27)
            Me.Label2.Name = "Label2"
            Me.Label2.Size = New System.Drawing.Size(39, 13)
            Me.Label2.TabIndex = 7
            Me.Label2.Text = "Nuovo"
            '
            'insAnno
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.ClientSize = New System.Drawing.Size(265, 80)
            Me.Controls.Add(Me.Label2)
            Me.Controls.Add(Me.Aggiungi)
            Me.Controls.Add(Me.newanno)
            Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
            Me.Name = "insAnno"
            Me.Text = "Inserisci Annualità"
            CType(Me.NewDataSet, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.AnniBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.AnniBindingSource1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.ResumeLayout(False)
            Me.PerformLayout()

        End Sub
        Friend WithEvents NewDataSet As NewDataSet
        Friend WithEvents AnniBindingSource As System.Windows.Forms.BindingSource
        Friend WithEvents AnniBindingSource1 As System.Windows.Forms.BindingSource
        Friend WithEvents newanno As System.Windows.Forms.TextBox
        Friend WithEvents Aggiungi As System.Windows.Forms.Button
        Friend WithEvents Label2 As System.Windows.Forms.Label

    End Class
End Namespace
